// Auto-generated by scripts/build-template.mjs
export const BASE_TEMPLATE = String.raw`<!DOCTYPE html>
<html lang="en" xmlns="http://www.w3.org/1999/xhtml">
<head>
  <meta charset="UTF-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>{{PAGE_TITLE}}</title>
  <style>
    body {
      margin: 0;
      padding: 0;
      background-color: #eef1f5;
    }

    table {
      border-collapse: collapse;
      border-spacing: 0;
      mso-table-lspace: 0pt;
      mso-table-rspace: 0pt;
    }

    td {
      padding: 0;
    }

    img {
      border: 0;
      display: block;
      line-height: 100%;
      outline: none;
      text-decoration: none;
    }

    a {
      text-decoration: none;
    }

    @media only screen and (max-width: 820px) {
      .email-shell {
        width: 100% !important;
      }

      .outer-pad {
        padding-left: 12px !important;
        padding-right: 12px !important;
      }

      .content-pad {
        padding-left: 20px !important;
        padding-right: 20px !important;
      }

      .card-pad {
        padding: 20px !important;
      }

      .stack-column,
      .stack-column td {
        display: block !important;
        width: 100% !important;
      }

      .stack-spacer {
        height: 20px !important;
        line-height: 20px !important;
      }

      .hero-title {
        font-size: 24px !important;
        line-height: 30px !important;
      }

      .hero-copy {
        font-size: 15px !important;
        line-height: 26px !important;
      }

      .summary-image {
        width: 100% !important;
        height: auto !important;
      }

      .spec-value {
        word-break: break-word !important;
        white-space: normal !important;
        text-align: right !important;
      }

      .cta-button {
        width: 176px !important;
      }

      .cta-button-link {
        font-size: 15px !important;
        line-height: 16px !important;
        padding: 14px 18px !important;
      }

      .feature-col {
        padding-left: 4px !important;
        padding-right: 4px !important;
      }

      .feature-row-cell {
        padding-top: 24px !important;
        padding-bottom: 24px !important;
      }

      .feature-icon-img {
        height: 20px !important;
        width: 20px !important;
      }

      .feature-label {
        font-size: 9px !important;
        line-height: 11px !important;
      }
    }
  </style>
</head>
<body style="margin: 0; padding: 0; background-color: #eef1f5;">
  <div style="display: none; max-height: 0; overflow: hidden; opacity: 0; mso-hide: all;">
    {{PREVIEW_TEXT}}
  </div>

  <table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0" style="width: 100%; background-color: #eef1f5;">
    <tr>
      <td class="outer-pad" align="center" style="padding: 24px 16px;">
        <!--[if mso]>
        <table role="presentation" width="800" cellpadding="0" cellspacing="0" border="0">
          <tr>
            <td>
        <![endif]-->
        <table role="presentation" class="email-shell" width="800" cellpadding="0" cellspacing="0" border="0" style="width: 100%; max-width: 800px; background-color: #f8f9fb; border: 1px solid #dfe4ea;">
          <tr>
            <td align="center" bgcolor="#0A0A0A" style="background-color: #0A0A0A; padding: 28px 40px;">
              <img
                src="{{LOGO_URL}}"
                alt="{{LOGO_ALT}}"
                width="214"
                style="display: block; width: 214px; max-width: 214px; height: auto;"
              />
            </td>
          </tr>

          <tr>
            <td class="content-pad" style="padding: 40px;">
              <table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0" style="width: 100%;">
                <tr>
                  <td class="hero-title" align="center" style="font-family: Arial, Helvetica, sans-serif; font-size: 30px; line-height: 36px; font-weight: 700; color: #191C1E; letter-spacing: -0.5px; padding-bottom: 16px;">
                    {{HERO_TITLE}}
                  </td>
                </tr>
                <tr>
                  <td class="hero-copy" style="font-family: Arial, Helvetica, sans-serif; font-size: 16px; line-height: 30px; color: #000000; padding-bottom: 24px;">
                    {{HERO_COPY}}
                  </td>
                </tr>
                {{CUSTOMER_INFO_SECTION}}

                <tr>
                  <td style="padding-bottom: 24px;">
                    <table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0" style="width: 100%; background-color: #ffffff; border: 1px solid #e7e8ea; border-radius: 16px;">
                      <tr>
                        <td class="card-pad" style="padding: 25px;">
                          <table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0">
                            <tr>
                              <td style="font-family: Arial, Helvetica, sans-serif; font-size: 18px; line-height: 28px; font-weight: 700; color: #191C1E; padding-bottom: 24px;">
                                Order summary
                              </td>
                            </tr>
                            <tr>
                              <td>
                                <table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0">
                                  <tr>
                                    <td class="stack-column" width="188" valign="top" style="width: 188px;">
                                      <img
                                        class="summary-image"
                                        src="{{PREVIEW_IMAGE_URL}}"
                                        alt="{{PREVIEW_IMAGE_ALT}}"
                                        width="188"
                                        style="display: block; width: 188px; height: 128px; border: 1px solid #42454E; border-radius: 4px;"
                                      />
                                    </td>
                                    <td class="stack-column" width="36" style="width: 36px;" aria-hidden="true">
                                      <div class="stack-spacer" style="line-height: 1px; font-size: 1px;">&nbsp;</div>
                                    </td>
                                    <td class="stack-column" valign="top">
                                      <table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0">
                                        <tr>
                                          <td style="font-family: Arial, Helvetica, sans-serif; font-size: 20px; line-height: 28px; font-weight: 700; color: #0A0A0F; padding-bottom: 8px;">
                                            {{PRODUCT_TITLE}}
                                          </td>
                                        </tr>
                                        <tr>
                                          <td style="font-family: Arial, Helvetica, sans-serif; font-size: 16px; line-height: 24px; color: #0A0A0F; padding-bottom: 20px;">
                                            {{PRODUCT_SUBTITLE}}
                                          </td>
                                        </tr>
                                        <tr>
                                          <td>
                                            {{OPTION_BADGES}}
                                          </td>
                                        </tr>
                                      </table>
                                    </td>
                                  </tr>
                                </table>
                              </td>
                            </tr>

                            {{CHANGE_REQUEST_SECTION}}
                          </table>
                        </td>
                      </tr>
                    </table>
                  </td>
                </tr>

                <tr>
                  <td style="padding-bottom: 24px;">
                    <table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0" style="width: 100%; background-color: #ffffff; border: 1px solid #e7e8ea; border-radius: 16px;">
                      <tr>
                        <td class="card-pad" style="padding: 25px;">
                          <table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0">
                            <tr>
                              <td style="font-family: Arial, Helvetica, sans-serif; font-size: 18px; line-height: 28px; font-weight: 700; color: #191C1E; padding-bottom: 16px;">
                                Specifications
                              </td>
                            </tr>

                            {{SPECIFICATION_ROWS}}
                          </table>
                        </td>
                      </tr>
                    </table>
                  </td>
                </tr>

                <tr>
                  <td style="padding-bottom: 24px;">
                    <table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0" style="width: 100%; background-color: #e7e8ea; border-radius: 16px;">
                      <tr>
                        <td class="card-pad" style="padding: 24px;">
                          <table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0">
                            <tr>
                              <td style="padding-bottom: 16px;">
                                <table role="presentation" cellpadding="0" cellspacing="0" border="0">
                                  <tr>
                                    <td width="20" valign="middle" style="width: 20px; padding-right: 12px; text-align: center; font-family: Arial, Helvetica, sans-serif; font-size: 18px; line-height: 20px; color: #005BB3;">
                                      &#9719;
                                    </td>
                                    <td valign="middle" style="font-family: Arial, Helvetica, sans-serif; font-size: 16px; line-height: 24px; font-weight: 700; color: #005BB3;">
                                      {{DELIVERY_LABEL}}
                                    </td>
                                  </tr>
                                </table>
                              </td>
                            </tr>
                            <tr>
                              <td style="font-family: Arial, Helvetica, sans-serif; font-size: 24px; line-height: 32px; font-weight: 700; color: #191C1E; padding-bottom: 16px;">
                                {{DELIVERY_RANGE}}
                              </td>
                            </tr>
                            {{ADDITIONAL_INSTRUCTIONS_SECTION}}
                          </table>
                        </td>
                      </tr>
                    </table>
                  </td>
                </tr>

                <tr>
                  <td align="center" style="padding-bottom: 24px;">
                    <table role="presentation" width="200" cellpadding="0" cellspacing="0" border="0" class="cta-button" style="margin: 0 auto; width: 200px;">
                      <tr>
                        <td align="center" bgcolor="#0070E6" style="background-color: #0070E6; background-image: linear-gradient(133.76deg, #00BFFF 0%, #0052CC 100%); border-radius: 8px;">
                          <a
                            href="{{CTA_URL}}"
                            class="cta-button-link"
                            style="display: block; font-family: Arial, Helvetica, sans-serif; font-size: 17px; line-height: 18px; font-weight: 700; color: #ffffff; padding: 16px 24px;"
                          >
                            {{CTA_TEXT}}
                          </a>
                        </td>
                      </tr>
                    </table>
                  </td>
                </tr>

                <tr>
                  <td class="feature-row-cell" style="border-top: 1px solid #edeef0; padding: 33px 0 32px;">
                    <table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0">
                      <tr>
                        <td class="feature-col" width="33.33%" align="center" valign="top" style="width: 33.33%; padding: 0 8px;">
                          <img
                            class="feature-icon-img"
                            src="https://cdn.shopify.com/s/files/1/0803/2216/7027/files/feature-nationwide-delivery.svg?v=1777018258"
                            alt=""
                            width="24"
                            height="24"
                            style="display: block; width: 24px; height: 24px; margin: 0 auto 8px;"
                          />
                          <div class="feature-label" style="font-family: Arial, Helvetica, sans-serif; font-size: 10px; line-height: 13px; font-weight: 700; color: #191C1E;">Nationwide Delivery</div>
                        </td>
                        <td class="feature-col" width="33.33%" align="center" valign="top" style="width: 33.33%; padding: 0 8px;">
                          <img
                            class="feature-icon-img"
                            src="https://cdn.shopify.com/s/files/1/0803/2216/7027/files/feature-replacement.svg?v=1777018258"
                            alt=""
                            width="24"
                            height="24"
                            style="display: block; width: 24px; height: 24px; margin: 0 auto 8px;"
                          />
                          <div class="feature-label" style="font-family: Arial, Helvetica, sans-serif; font-size: 10px; line-height: 13px; font-weight: 700; color: #191C1E;">1:1 Replacement</div>
                        </td>
                        <td class="feature-col" width="33.33%" align="center" valign="top" style="width: 33.33%; padding: 0 8px;">
                          <img
                            class="feature-icon-img"
                            src="https://cdn.shopify.com/s/files/1/0803/2216/7027/files/feature-warranty-service.svg?v=1777018258"
                            alt=""
                            width="24"
                            height="24"
                            style="display: block; width: 24px; height: 24px; margin: 0 auto 8px;"
                          />
                          <div class="feature-label" style="font-family: Arial, Helvetica, sans-serif; font-size: 10px; line-height: 13px; font-weight: 700; color: #191C1E;">Warranty &amp; Service</div>
                        </td>
                      </tr>
                    </table>
                  </td>
                </tr>
              </table>
            </td>
          </tr>

          <tr>
            <td align="center" bgcolor="#171433" style="background-color: #171433; padding: 20px 32px 40px;">
              <table role="presentation" cellpadding="0" cellspacing="0" border="0" style="margin: 0 auto 20px;">
                <tr>
                  <td style="padding: 0 8px;">
                    <a href="{{FACEBOOK_URL}}" style="display: inline-block; width: 40px; height: 40px; border: 1px solid #ffffff; border-radius: 20px; font-family: Arial, Helvetica, sans-serif; font-size: 16px; line-height: 40px; font-weight: 700; text-align: center; color: #ffffff;">f</a>
                  </td>
                  <td style="padding: 0 8px;">
                    <a href="{{INSTAGRAM_URL}}" style="display: inline-block; width: 40px; height: 40px; border: 1px solid #ffffff; border-radius: 20px; font-family: Arial, Helvetica, sans-serif; font-size: 13px; line-height: 40px; font-weight: 700; text-align: center; color: #ffffff;">IG</a>
                  </td>
                  <td style="padding: 0 8px;">
                    <a href="{{TWITTER_URL}}" style="display: inline-block; width: 40px; height: 40px; border: 1px solid #ffffff; border-radius: 20px; font-family: Arial, Helvetica, sans-serif; font-size: 16px; line-height: 40px; font-weight: 700; text-align: center; color: #ffffff;">T</a>
                  </td>
                  <td style="padding: 0 8px;">
                    <a href="{{LINKEDIN_URL}}" style="display: inline-block; width: 40px; height: 40px; border: 1px solid #ffffff; border-radius: 20px; font-family: Arial, Helvetica, sans-serif; font-size: 13px; line-height: 40px; font-weight: 700; text-align: center; color: #ffffff;">in</a>
                  </td>
                </tr>
              </table>

              <table role="presentation" cellpadding="0" cellspacing="0" border="0" style="margin: 0 auto;">
                <tr>
                  <td align="center" style="font-family: Arial, Helvetica, sans-serif; font-size: 12px; line-height: 20px; color: #ffffff;">
                    {{COMPANY_ADDRESS}}<br />
                    Phone: {{SUPPORT_PHONE}}<br />
                    Email: {{SUPPORT_EMAIL}}
                  </td>
                </tr>
              </table>
            </td>
          </tr>
        </table>
        <!--[if mso]>
            </td>
          </tr>
        </table>
        <![endif]-->
      </td>
    </tr>
  </table>
</body>
</html>
`;
